### ISSUE TITLE
training

### ISSUE THREAD

**Issue by Mohsin-Sial099** [faizan1234567/Brats-20-Tumors-segmentation#2]
how to train a model?

**Comment by faizan1234567** [comment]
here is the script.
``
python train.py -h
optional arguments:
  -h, --help            show this help message and exit
  --data DATA           dataset root directory path
  --fold FOLD           folder name
  --json_file JSON_FILE
                        path to json file
  --batch BATCH         batch size
  --img_roi IMG_ROI     image roi size
  --val_every VAL_EVERY
                        validate every 2 epochs
  --max_epochs MAX_EPOCHS
                        maximum number of epoch to train
  --workers WORKERS     Number of data loading workers
  --pretrained_model PRETRAINED_MODEL
                        path to pretraiend model
  --pretrained          use pretrained weights.
  --resume              starting training from the saved ckpt.
  --platform_changed    pc changed, so that dataset dir has been set accordingly

python train.py --data <dataset-dir> --fold 0 --json_file <dataset-split-file-path>
 --batch 1 --workers 8 --val_every 2 --max_epochs 100 --pretrained_model <pretrained-model-path> 
``

**Comment by Mohsin-Sial099** [comment]
thats great

**Comment by mirfan899** [comment]
Can you share the link to json file. I dont see it on dataset on official site.

**Comment by faizan1234567** [comment]
@mirfan899
here is the json file: https://github.com/faizan1234567/BraTS23-Tumors-Segmentation/blob/main/media/json_file/dataset.json
